--------DAY 6------------
------DML------
UPDATE TABLE_NAME
SET COLUMN_NAME = (SUBQUERY , DEAFULT) , [COLUMN_NAME = VALUE]
WHERE CONDITION

-----------SUBQUERY 가능-----
UPDATE EMPLOYEE
SET JOB_ID = (SELECT JOB_ID 
              FROM EMPLOYEE
              WHERE EMP_NAME = '성해교') , DEPT_ID = '50'
WHERE EMP_NAME =  '심하균'

------------DEFAULT 쓰면 봐뀐다-------
UPDATE EMPLOYEE
SET MARRIAGE = DEFAULT
WHERE EMP_ID = '210'


------외래키 업데이트------
UPDATE EMPLOYEE
SET DEPT_ID = '65'
WHERE DEPT_ID IS NULL

-- DML ( 트랜잭션 - COMMIT , ROLLBACK )

--- DELETE
DELETE TABLE_NAME
WHERE CONDITION

SELECT *
FROM LOCATION

SELECT *
FROM DEPARTMENT

DELETE TABLE_NAME
WHERE CONDITION

--------------------------------
-------- 부모키 자식키 
--INSERT    O     X
--UPDATE    X     O
--DELETE    X     O

--- 전체 레코드를 삭제할 때는 TRUNCATE가 좋다 (더 빠름)
TRUNCATE TABLE TABLE-NAME ;

--TRANSCACTION @@@@@@@@@@@@@@@@@@@@
SELECT *
FROM SAL_GRADE

DELETE
FROM SAL_GRADE ;

----CMD
SQLPLUS HR/HR
SELECT *FROM SAL_GRADE

--오라클에서는 안보이지만 CMD창에서는 보인다

ROLLBACK ;

CREATE SEQUENCE SEQUENCE_NAME
START WITH 101 ;

SELECT SEQUENCE_NAME.nextval
FROM DUAL

-----------WORK BOOK ------------
---------MEMBER TABLE---------

CREATE TABLE MEMBER (
      MEMBER_ID     NUMBER(10) PRIMARY KEY ,
      NAME   VARCHAR2(25) NOT NULL ,
      ADDRESS VARCHAR2(100)  ,
      CITY VARCHAR2(30) ,
      PHONE VARCHAR2(15)  ,
      JOIN_DATE DATE DEFAULT SYSDATE NOT NULL  ) ; 
      
SELECT *
FROM MEMBER
---------TITLE TABLE---------

CREATE TABLE TITLE (
      TITLE_ID     NUMBER(10) PRIMARY KEY ,
      TITLE   VARCHAR2(60) NOT NULL ,
      DESCRIPTION VARCHAR2(400) NOT NULL  ,
      RATING VARCHAR2(20) CHECK (RATING IN ('18가','15가','전체가','12가') ),
      CATEGORY VARCHAR2(20) CHECK (CATEGORY IN ('드라마','코미디','액션','아동','SF','다큐멘터리'))  ,
      RELEASE_DATE DATE ) ;   
      
---------TITLE_COPY TABLE -----------

CREATE TABLE TITLE_COPY(
      COPY_ID     NUMBER(10) ,
      TITLE_ID   NUMBER(10) ,
      STATUS VARCHAR2(20) NOT NULL CHECK (STATUS IN ('대여가능','파손','대여중','예약'))  ,
         FOREIGN KEY (TITLE_ID) REFERENCES TITLE(TITLE_ID) ,
      PRIMARY KEY (COPY_ID , TITLE_ID)
        ) ;
        
SELECT *
FROM TITLE_COPY

DROP TABLE TITLE_COPY
        
---------RENTAL -----------

CREATE TABLE RENTAL (
      BOOK_DATE   DATE DEFAULT SYSDATE ,
      MEMBER_ID   NUMBER(10) ,
      COPY_ID  NUMBER(10)  ,
      TITLE_ID NUMBER(10)  ,
      ACT_RET_DATE DATE ,
      EXP_RET_DATE DATE DEFAULT SYSDATE+2 ,
         FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ,
         FOREIGN KEY (COPY_ID , TITLE_ID) REFERENCES TITLE_COPY(COPY_ID ,TITLE_ID) ,
         PRIMARY KEY (BOOK_DATE , MEMBER_ID , COPY_ID , TITLE_ID)
        ) ;

DROP TABLE RENTAL

SELECT *
FROM RENTAL



--------------RESERVATION----------

CREATE TABLE RESERVATION (
      RES_DATE     DATE ,
      MEMBER_ID   NUMBER(10) ,
      TITLE_ID NUMBER(10)  ,
         FOREIGN KEY (TITLE_ID) REFERENCES TITLE(TITLE_ID) ,
         FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ,
      PRIMARY KEY (RES_DATE , TITLE_ID ,MEMBER_ID)
        ) ;
        
DROP TABLE RESERVATION


SELECT *
FROM RESERVATION

----------Q2-------------
CREATE SEQUENCE MEMBER_ID_SEQ
START WITH 101 ;

DROP SEQUENCE MEMBER_ID_SEQ

CREATE SEQUENCE TITLE_ID_SEQ
START WITH 92 ;

---------Q3---------------
SELECT *
FROM TITLE

DELETE  TITLE

    
INSERT INTO TITLE VALUES(TITLE_ID_SEQ.NEXTVAL, '인어공주' , '인어공주 설명' , '전체가', '아동', '951005') ,
INSERT INTO TITLE VALUES(TITLE_ID_SEQ.NEXTVAL, '매트릭스' , '매트릭스 설명' , '15가', 'SF', '950519') ,
INSERT INTO TITLE VALUES(TITLE_ID_SEQ.NEXTVAL, '에이리언' , '에이리언 설명' , '18가', 'SF', '950812') ,
INSERT INTO TITLE VALUES(TITLE_ID_SEQ.NEXTVAL, '모던타임즈' , '모던타임즈 설명' , '전체가', '코미디', '950712') ,
INSERT INTO TITLE VALUES(TITLE_ID_SEQ.NEXTVAL, '러브스토리' , '러브스토리 설명' , '전체가', '드라마', '950912') ,
INSERT INTO TITLE VALUES(TITLE_ID_SEQ.NEXTVAL, '람보' , '람보 설명' , '18가', '액션', '950601')

------------Q4------------------------------------
SELECT *
FROM MEMBER

INSERT INTO MEMBER VALUES(MEMBER_ID_SEQ.NEXTVAL, '김철수' , '강남구' , '서울', '899-6666', '900308')
INSERT INTO MEMBER VALUES(MEMBER_ID_SEQ.NEXTVAL, '이영희' , '서면' , '부산', '355-8882', '900308')
INSERT INTO MEMBER VALUES(MEMBER_ID_SEQ.NEXTVAL, '최진국' , '동광양' , '제주' , '852-5764', '910617')
INSERT INTO MEMBER VALUES(MEMBER_ID_SEQ.NEXTVAL, '강준호' , '홍제동' , '강릉' , '559-7777', '900407')
INSERT INTO MEMBER VALUES(MEMBER_ID_SEQ.NEXTVAL, '민병국' , '전민동' , '대전' , '559-8741', '910118')
INSERT INTO MEMBER VALUES(MEMBER_ID_SEQ.NEXTVAL, '오민수' , '북구' , '광주' , '542-9988' , '910118')

---------------------Q5---------------------------
SELECT *
FROM TITLE_COPY
 SELECT TITLE_ID FROM TITLE WHERE TITLE = '인어공주'

INSERT INTO TITLE_COPY VALUES( '1' , (SELECT TITLE_ID FROM TITLE WHERE TITLE = '인어공주') , '대여가능')
INSERT INTO TITLE_COPY VALUES( '1' , (SELECT TITLE_ID FROM TITLE WHERE TITLE = '매트릭스') , '대여가능')
INSERT INTO TITLE_COPY VALUES( '2' , (SELECT TITLE_ID FROM TITLE WHERE TITLE = '매트릭스') , '대여중')
INSERT INTO TITLE_COPY VALUES( '1' , (SELECT TITLE_ID FROM TITLE WHERE TITLE = '에이리언') , '대여가능')
INSERT INTO TITLE_COPY VALUES( '1' , (SELECT TITLE_ID FROM TITLE WHERE TITLE = '모던타임즈') , '대여가능')
INSERT INTO TITLE_COPY VALUES( '2' , (SELECT TITLE_ID FROM TITLE WHERE TITLE = '모던타임즈') , '대여가능')
INSERT INTO TITLE_COPY VALUES( '3' , (SELECT TITLE_ID FROM TITLE WHERE TITLE = '모던타임즈') , '대여중')
INSERT INTO TITLE_COPY VALUES( '1' , (SELECT TITLE_ID FROM TITLE WHERE TITLE = '러브스토리') , '대여가능')
INSERT INTO TITLE_COPY VALUES( '1' , (SELECT TITLE_ID FROM TITLE WHERE TITLE = '람보') , '대여가능')

SELECT TITLE , COPY_ID , STATUS
FROM TITLE_COPY
JOIN TITLE USING (TITLE_ID)

--------------Q6------------------

SELECT *
FROM RENTAL

SELECT MEMBER_ID FROM MEMBER WHERE NAME = '김철수'

INSERT INTO RENTAL VALUES( SYSDATE-3 , (SELECT MEMBER_ID FROM MEMBER WHERE NAME = '김철수'),1 ,(SELECT TITLE_ID FROM TITLE WHERE TITLE = '인어공주') ,SYSDATE-2 ,SYSDATE -1)
INSERT INTO RENTAL VALUES( SYSDATE-1 , (SELECT MEMBER_ID FROM MEMBER WHERE NAME = '최진국'),2 ,(SELECT TITLE_ID FROM TITLE WHERE TITLE = '매트릭스') , NULL ,SYSDATE +1)
INSERT INTO RENTAL VALUES( SYSDATE-2 , (SELECT MEMBER_ID FROM MEMBER WHERE NAME = '강준호'),3 ,(SELECT TITLE_ID FROM TITLE WHERE TITLE = '모던타임즈') , NULL ,SYSDATE )
INSERT INTO RENTAL VALUES( SYSDATE-4 , (SELECT MEMBER_ID FROM MEMBER WHERE NAME = '민병국'),1 ,(SELECT TITLE_ID FROM TITLE WHERE TITLE = '람보') ,SYSDATE-2 ,SYSDATE -2)

SELECT TITLE ,C.COPY_ID ,NAME , BOOK_DATE ,EXP_RET_DATE , ACT_RET_DATE
FROM RENTAL R
JOIN MEMBER M USING (MEMBER_ID)
JOIN TITLE_COPY C ON (R.COPY_ID = C.COPY_ID) AND (R.TITLE_ID = C.TITLE_ID)
JOIN TITLE T ON (C.TITLE_ID = T.TITLE_ID)

---------------Q7------------

CREATE OR REPLACE VIEW TITLE_AVAIL
AS SELECT TITLE , C.COPY_ID ,STATUS , EXP_RET_DATE
FROM TITLE T
LEFT JOIN TITLE_COPY C ON (T.TITLE_ID = C.TITLE_ID)
LEFT JOIN RENTAL R ON (R.COPY_ID = C.COPY_ID) AND (R.TITLE_ID = C.TITLE_ID)

DROP VIEW TITLE_AVAIL

SELECT *
FROM TITLE_AVAIL

--------------Q8-----------------
INSERT INTO TITLE VALUES(TITLE_ID_SEQ.NEXTVAL, '스타워즈' , '스타워즈 설명' , '전체가', 'SF', '770707')

SELECT *
FROM TITLE
ORDER BY 1

INSERT INTO TITLE_COPY VALUES( '1' , (SELECT TITLE_ID FROM TITLE WHERE TITLE = '스타워즈') , '대여가능')
INSERT INTO TITLE_COPY VALUES( '2' , (SELECT TITLE_ID FROM TITLE WHERE TITLE = '스타워즈') , '대여가능')

SELECT *
FROM TITLE_COPY

SELECT *
FROM RESERVATION

DELETE RESERVATION

SELECT MEMBER_ID FROM MEMBER  WHERE NAME = '이영희'
SELECT TITLE_ID FROM TITLE WHERE TITLE = '스타워즈'

INSERT INTO RESERVATION VALUES( SYSDATE , (SELECT MEMBER_ID FROM MEMBER  WHERE NAME = '이영희') , (SELECT TITLE_ID FROM TITLE WHERE TITLE = '스타워즈'))
INSERT INTO RESERVATION VALUES( SYSDATE , (SELECT MEMBER_ID FROM MEMBER  WHERE NAME = '오민수') , (SELECT TITLE_ID FROM TITLE WHERE TITLE = '러브스토리'))

SELECT *
FROM RESERVATION

DELETE RESERVATION
WHERE MEMBER_ID = (SELECT MEMBER_ID FROM MEMBER  WHERE NAME = '이영희')

SELECT *
FROM RESERVATION

INSERT INTO RENTAL VALUES( SYSDATE , (SELECT MEMBER_ID FROM MEMBER WHERE NAME = '이영희'),1 ,(SELECT TITLE_ID FROM TITLE WHERE TITLE = '스타워즈') , NULL ,SYSDATE+2  )

SELECT *
FROM RENTAL

DELETE RENTAL
WHERE MEMBER_ID = (SELECT MEMBER_ID FROM MEMBER  WHERE NAME = '이영희')

SELECT *
FROM TITLE_COPY

UPDATE TITLE_COPY
SET STATUS = '대여중'
WHERE COPY_ID = 1
AND TITLE_ID = (SELECT TITLE_ID FROM TITLE WHERE TITLE = '스타워즈')

---------------Q9--------------------

ALTER TABLE TITLE ADD PRICE NUMBER(5)

SELECT *
FROM TITLE
ORDER BY 1

UPDATE TITLE
SET PRICE = 1500
WHERE TITLE_ID = 98 ;

ALTER TABLE TITLE MODIFY PRICE NUMBER(5) NOT NULL

------------Q10--------------------
SELECT *
FROM RENTAL

UPDATE RENTAL
SET ACT_RET_DATE = NULL
WHERE MEMBER_ID = 102

SELECT NAME AS 회원명 ,
       TITLE AS 제목 ,
       BOOK_DATE AS 대여일 ,
       ACT_RET_DATE - BOOK_DATE AS 대여기간
      
       
FROM RENTAL R
JOIN MEMBER M USING (MEMBER_ID)
JOIN TITLE_COPY C ON (R.COPY_ID = C.COPY_ID) AND (R.TITLE_ID = C.TITLE_ID)
JOIN TITLE T ON (C.TITLE_ID = T.TITLE_ID)
